### ISSUE TITLE
Consider making networking optional

### ISSUE THREAD

**Issue by matklad** [ArturKovacs/emulsion#1]
Hi!

I've tried to build emulsion from source, and it failed due to openssl dependency (native libraries are not trivial on NixOS). This is made me raise my eyebrow, as it seems like there should be no reason for an image viewer to do crypto/networking. 

Looking at the source code, it looks like this dependency is there because of the auto-update functionality. Auto-updates (and, in general, network access) come with security and privacy implications, so it would be cool if this feature was opt-in.

Moreover, my gut feeling is that auto-update should be managed by a tool outside of the application itself.

**Comment by ArturKovacs** [comment]
Hi!

Thanks for posting an issue. I haven't even considered this but I'll make networking as an optional feature soon.

**Comment by ArturKovacs** [comment]
This should be solved by 916451b299413f25485cd3f47a7ec85fd7aa6598. Let me know if it satisfies this request or if something is missing.

**Comment by ArturKovacs** [comment]
I would like to encourage everyone interested in this to also take a look at #24

**Comment by ArturKovacs** [comment]
Alright networking is now a non-default feature with #24 merged. I'm closing this now. As always feel free to add new comments if you think this needs to be reoopened for any reason.
