### ISSUE TITLE
Order files case-insensitively

### ISSUE THREAD

**Issue by Aloso** [ArturKovacs/emulsion#102]
Files are usually sorted alphabetically and case-insensitively. Therefore it's confusing that emulsion sorts uppercase file names before lowercase files.

Ideally, files should also be sorted lexically (e.g. `e E é É è È ĕ Ĕ ê Ê ě Ě ë Ë ė Ė ȩ Ȩ ę Ę ē Ē ȅ Ȅ ȇ Ȇ` should all come between `D` and `F`), but this is much harder, so let's concentrate on case insensitivity first.

**Comment by Aloso** [comment]
I made a new crate that can handle lexical, natural and case-insensitive sorting: https://github.com/Aloso/lexical-sort

I did a very simple benchmark, and it doesn't seem to be much slower than the `alphanumeric-sort` crate. Are you okay with using this?

**Comment by ArturKovacs** [comment]
> emulsion sorts uppercase file names before lowercase files.

Wow I did not know this.

> Are you okay with using this?

Yes I'd be happy to use your crate :)
