### ISSUE TITLE
File type determined by file extension only

### ISSUE THREAD

**Issue by Shnatsel** [ArturKovacs/emulsion#103]
Right now file type seems to be determined by file extension alone. So if I have an image with .png extension that's actually a JPEG, emulsion will fail to open it.

Meanwhile elementary Photos, gThumb and even Firefox handle such cases without issue by guessing the file type by the file header. `image` crate already supports this, and if this turns out to be a performance issue then it can only be done if decoding with the advertised format fails.

Simple example showing automatic format detection in `image`:
```rust
fn main() -> std::io::Result<()> {
    let path = std::env::args().skip(1).next().unwrap();
    let _ = image::io::Reader::open(path)?
        .with_guessed_format()
        .unwrap()
        .decode()
        .unwrap();
    Ok(())
}
```

**Comment by ArturKovacs** [comment]
The format detection from contents was implemented by @Aloso as per #98 which was merged today; so I'm closing this at this is already resolved.
