### ISSUE TITLE
Release of 3.0 on crates.io

### ISSUE THREAD

**Issue by HeroicKatora** [ArturKovacs/emulsion#114]
The git tags mention a release `3.0` yet no such version is published on [`crates.io`](https://crates.io/crates/emulsion). Do you have intentions to publish it there too?

**Comment by ArturKovacs** [comment]
Yeah it's a bit messy to release to creates.io due to having to release gelatin separately. Anyways I'll make a v3.1 release.

**Comment by ArturKovacs** [comment]
Actually it should be v4.0 to respect the rules of semantic versioning as the lastest on the master sorts images differently then v3.0 (it has non-case-sensitive sorting #112)

**Comment by HeroicKatora** [comment]
Would be fine, any with `apng` support would do :+1:

**Comment by HeroicKatora** [comment]
Also Github just half-ruined your profile picture's layout by making it an actual circle :(

**Comment by ArturKovacs** [comment]
Yeah I'm not a fan of circular profile pictures but I'ts okay, a bit of change every once in while doesn't hurt. Also I think this profile picture still kinda works with the circular frame. I've seen (and had) ones that much work much worse.

As far as the release is concerend it's published so I'll close this. :)
