### ISSUE TITLE
Slider should use rectangle instead of vertical line

### ISSUE THREAD

**Issue by Aloso** [ArturKovacs/emulsion#123]
I would prefer if the slider used a rectangle instead of a vertical line, like a scroll bar. Besides looking more familiar, it also gives you an intuition how many images are in the folder (the bigger the rectangle, the fewer images are there).

I'd like to hear more opinions on this, before submitting a PR. I made some screenshots with a gray or a green slider:

<details>
<summary><b>Click to expand</b></summary>

![gray dark](https://user-images.githubusercontent.com/15658558/85728869-98355c80-b6f8-11ea-8282-75fcdeb0bda6.png)

![gray light](https://user-images.githubusercontent.com/15658558/85728967-af744a00-b6f8-11ea-9c22-858d9c389a34.png)

![green dark](https://user-images.githubusercontent.com/15658558/85728994-b438fe00-b6f8-11ea-965e-79ace1b85b36.png)

![green light](https://user-images.githubusercontent.com/15658558/85729006-b733ee80-b6f8-11ea-90d1-66ef272d5ec9.png)

</details>

**Comment by ArturKovacs** [comment]
I have mixed feelings about this.

On one hand this gives a nice feedback about the number of images in the folder but on the other it feels it introduces an incosistency in the aesthetics. 

It would be nice if there would be a solution that brings the best of both but right now I'm leaning towards keeping the line.

**Comment by ArturKovacs** [comment]
Please make a PR, I'd like to try some variations of this :)

**Comment by ArturKovacs** [comment]
It's been a while. I'm still not convinced that the slider thickness should be proportional to the number of elements in the folder. I'll colse this for now but I'll keep this in the back of my mind.
