### ISSUE TITLE
List of supported MIME types on Linux is empty

### ISSUE THREAD

**Issue by Shnatsel** [ArturKovacs/emulsion#127]
In the .desktop file shipped in emulsion 4.0.0 deb package the `MimeType` field is empty. This prevents opening images directly in Emulsion from the file manager or other programs.

Full contents of the .desktop file for reference:
```
[Desktop Entry]
Encoding=UTF-8
Comment=A lightweight and minimalistic image viewer
Exec=emulsion %f
Icon=emulsion
Name=Emulsion
Terminal=false
Type=Application
MimeType=
Version=4.0.0
```

**Comment by ArturKovacs** [comment]
Which desktop environment are you using? I tested with GNOME and I could locate Emulsion in the open with dialogue when showing all applications.

**Comment by Shnatsel** [comment]
I use Pantheon (elementary OS), but the relevant code on it should be shared with GNOME. The .desktop file specification is [standardized](https://specifications.freedesktop.org/desktop-entry-spec/latest/) and independent from the desktop environment anyway.

Emulsion shows up when I bring up *all* applications; however, it does not declare that it supports JPEG/PNG/GIF formats, so it's not shown in "Open with" for those formats by default, I have to go through extra steps to get it there.

The listing of supported mime types for an image viewer should actually list the supported formats, like this: https://github.com/elementary/photos/blob/0d20e8d7afcc4bbb5c56a4fdc207857d567adb73/data/io.elementary.photos-viewer.desktop.in.in#L10

**Comment by Aloso** [comment]
I made a list of MIME types for emulsion:

```properties
image/jpeg
image/jpg
image/pjpeg
image/png
image/apng
image/gif
image/webp
image/tiff
image/bmp
image/avif   # 1
image/x-png
image/x-tga
image/x-targa
image/x-bmp
image/x-icon
image/vnd.radiance   # 2
image/x‑portable‑bitmap
image/x‑portable‑graymap
image/x‑portable‑pixmap
image/x‑portable‑anymap
image/x-3fr   # 3
image/x-fff   # 3
image/x-iiq   # 3
application/vnd.comicbook+zip   # 4
application/vnd.comicbook-rar   # 4
application/x-cbr   # 4
application/x-cbt   # 4
```

Notes:

1. supported with the `avif` feature
2. `image/vnd.radiance` is the MIME type for HDR files
3. I noticed that `3fr`, `fff` and `iiq` files are (at least partially) supported by emulsion, they should be added to the allowed file endings as well
4. These MIME types will be supported when support for comic book archives lands

**Comment by ArturKovacs** [comment]
I did include `image/avif`in the merged PR, installed from the new deb and yet my GNOME desktop doesn't handle Emulsion as if it supports that type.

![image](https://user-images.githubusercontent.com/8320264/90307578-bab54c00-ded7-11ea-9275-e81a219e13a9.png)

**Comment by paolobarbolini** [comment]
The issue is probably that `image/avif` isn't in the mime type database yet.

**Comment by ArturKovacs** [comment]
I guess we could solve this with a post installation script. The issue is that `cargo-bundle` doesn't support that afaik. So a PR would have to be made for `cargo-bundle` to do that.

Honestly I'm much less motivated to work on this instead of other Emulsion issues; esspecially because Emulsion still shows up in the "all applications" list.
