### ISSUE TITLE
Crash on app open

### ISSUE THREAD

**Issue by RagibHasin** [ArturKovacs/emulsion#128]
On Windows the app crashes upon run without displaying any UI or image.

Content of `panic.txt` below
```
===

--
buffering RedrawRequested event
--

Location /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\src\libstd\macros.rs:13:23

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: DefSubclassProc
   8: DefSubclassProc
   9: CallWindowProcW
  10: CallWindowProcW
  11: glPushClientAttrib
  12: CallWindowProcW
  13: DispatchMessageW
  14: IsWindowVisible
  15: KiUserCallbackDispatcher
  16: NtUserDispatchMessage
  17: DispatchMessageW
  18: InputFocusMonitorCreate
  19: InputFocusMonitorCreate
  20: TF_Notify
  21: TF_Notify
  22: TF_SendLangBandMsg
  23: <unknown>
  24: DllUnregisterServer
  25: TF_SendLangBandMsg
  26: TF_SendLangBandMsg
  27: TF_SetDefaultRemoteKeyboardLayout
  28: SetInputScopes2
  29: CtfImeProcessCicHotkey
  30: CtfImeProcessCicHotkey
  31: CtfImeAssociateFocus
  32: CtfImeAssociateFocus
  33: CtfImeAssociateFocus
  34: ImmSetActiveContext
  35: GetWindow
  36: GetWindowRgnBox
  37: GetDlgItem
  38: GetDlgItem
  39: CallWindowProcW
  40: DispatchMessageW
  41: IsWindowVisible
  42: KiUserCallbackDispatcher
  43: NtUserMessageCall
  44: GetWindowTextW
  45: GetWindowTextW
  46: CallWindowProcW
  47: CallWindowProcW
  48: DefSubclassProc
  49: DefSubclassProc
  50: DefSubclassProc
  51: DefSubclassProc
  52: CallWindowProcW
  53: CallWindowProcW
  54: glPushClientAttrib
  55: CallWindowProcW
  56: DispatchMessageW
  57: IsWindowVisible
  58: KiUserCallbackDispatcher
  59: NtUserShowWindow
  60: <unknown>
  61: <unknown>
  62: <unknown>
  63: <unknown>
  64: <unknown>
  65: <unknown>
  66: <unknown>
  67: BaseThreadInitThunk
  68: RtlUserThreadStart

===
```

**Comment by ArturKovacs** [comment]
Thanks for opening an issue.

There is no function call from the emulsion source in this call-stack which leads me to suspect that this error isn't caused by a bug in Emulsion.

I'm wondering if there's something particular about the system on which you are trying to run Emulsion. For example if it's a virtual machine or it runs an older version Windows like Windows 7.

**Comment by ArturKovacs** [comment]
@RagibHasin this issue cannot move on without the following information from you

- Which version of windows are you using (eg Win 7)?
- Is it 32bit or 64bit
- Is it running on a virtual machine?
- What is the GPU in your machine?
- Is there anything else that would help reproduce the problem?

Currently it really seems to me that this environemnt is simply not supported by Emulsion and I don't see how this error could be reproduced.

**Comment by RagibHasin** [comment]
Sorry for late, @ArturKovacs .

My system is
- not a VMm
- running 64 bit Windows 10 1909 (18363.900)
- an ASUS Zenbook UM462
- with Ryzen 5 3400U processor and integrated Radeon Vega graphics.

**Comment by ArturKovacs** [comment]
My main development platform is a 64bit Window 10 and I've never seen this. I'm just shooting in the dark here; but are you running a screen capture application or any software that attaches itself to other programs? Maybe you are using a custom theme or something that somehow modifies windows.

Otherwise I'm pretty clueless. I'm not sure if you use Rust, but would you mind installing [Rust](https://www.rust-lang.org/learn/get-started) and then trying to execute emulsion in debug mode by invoking `cargo run` from a cmd window that's navigated to the source folder?

**Comment by Aloso** [comment]
It might be a good idea to run emulsion in the command line (open cmd.exe or powershell and enter `emulsion`). Maybe there is something logged besides the panic message.

**Comment by Aloso** [comment]
@ArturKovacs It might be a good idea to add a `--verbose` option to track down bugs like this more easily.

**Comment by ArturKovacs** [comment]
> Please run emulsion in a command line (open cmd.exe or powershell and enter emulsion). Maybe there is something logged besides the panic message. Compiling it in debug mode might not be necessary.

Nope, unfortunately that's not going to work 😕

Windows is a cheeky boy and you have to decide at compile time if your program is command line or windowed. If you compile it as command line it will always bring up a cmd window even if you run it from the desktop environment. So emulsion is compiled as windowed in release build. But if you compile a program as windowed you don't get the standard output even if you run it from a command line interface.

> It might be a good idea to add a `--verbose` option to track down bugs like this more easily.

To what command should the `--verbose` be added?

**Comment by Aloso** [comment]
> you have to decide at compile time if your program is command line or windowed

Sorry, I didn't know that.

> To what command should the `--verbose` be added?

My idea was that running `emulsion --verbose` would print debugging information. But using env variables might actually be better (with `env_logger`, that would be `RUST_LOG=info emulsion`)

**Comment by ArturKovacs** [comment]
> My idea was that running emulsion --verbose would print debugging information.

I'm not against something like this but I think many issues which are currently open are higher priority.

**Comment by RagibHasin** [comment]
I'm currently away from my laptop. And, yes, I use Rust. I'll try running `cargo run` as soon as get the chance to.

Also, I don’t have any screen recording app running. I use the built in Windows dark theme, though, nothing external to modify my UI.

**Comment by RagibHasin** [comment]
Result of `cargo run` follows

<pre>
$ cargo run
warning: variable does not need to be mutable
   --> src\picture_widget.rs:590:10
    |
590 |                     let mut borrowed = self.data.borrow_mut();
    |                         ----^^^^^^^^
    |                         |
    |                         help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 3.44s
     Running `target\debug\emulsion.exe`

Panic happened

--
buffering RedrawRequested event
--

Location C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop\runner.rs:110:17

   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.48\src\backtrace\dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized<closure-0>
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.48\src\backtrace\mod.rs:66
   2: backtrace::backtrace::trace<closure-0>
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.48\src\backtrace\mod.rs:53
   3: backtrace::capture::Backtrace::create
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.48\src\capture.rs:164
   4: backtrace::capture::Backtrace::new
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.48\src\capture.rs:128
   5: emulsion::handle_panic::handle_panic
             at src\handle_panic.rs:14
   6: core::ops::function::Fn::call<fn(core::panic::PanicInfo*),(core::panic::PanicInfo*)>
             at C:\Users\ragib\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:72
   7: std::panicking::rust_panic_with_hook
             at /rustc/67100f61e62a86f2bf9e38552ee138e231eddc74\/src\libstd\panicking.rs:477
   8: std::panicking::begin_panic<str*>
             at C:\Users\ragib\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:403
   9: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event<()>
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop\runner.rs:110
  10: winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop.rs:102
  11: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop.rs:686
  12: DefSubclassProc
  13: DefSubclassProc
  14: CallWindowProcW
  15: CallWindowProcW
  16: glPushClientAttrib
  17: CallWindowProcW
  18: DispatchMessageW
  19: IsWindowVisible
  20: KiUserCallbackDispatcher
  21: NtUserDispatchMessage
  22: DispatchMessageW
  23: InputFocusMonitorCreate
  24: InputFocusMonitorCreate
  25: TF_Notify
  26: TF_Notify
  27: TF_SendLangBandMsg
  28: <unknown>
  29: DllUnregisterServer
  30: TF_SendLangBandMsg
  31: TF_SendLangBandMsg
  32: TF_SetDefaultRemoteKeyboardLayout
  33: SetInputScopes2
  34: CtfImeProcessCicHotkey
  35: CtfImeProcessCicHotkey
  36: CtfImeAssociateFocus
  37: CtfImeAssociateFocus
  38: CtfImeAssociateFocus
  39: ImmSetActiveContext
  40: GetWindow
  41: GetWindowRgnBox
  42: GetDlgItem
  43: GetDlgItem
  44: CallWindowProcW
  45: DispatchMessageW
  46: IsWindowVisible
  47: KiUserCallbackDispatcher
  48: NtUserMessageCall
  49: GetWindowTextW
  50: GetWindowTextW
  51: CallWindowProcW
  52: CallWindowProcW
  53: DefSubclassProc
  54: DefSubclassProc
  55: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop.rs:1737
  56: DefSubclassProc
  57: DefSubclassProc
  58: CallWindowProcW
  59: CallWindowProcW
  60: glPushClientAttrib
  61: CallWindowProcW
  62: DispatchMessageW
  63: IsWindowVisible
  64: KiUserCallbackDispatcher
  65: NtUserShowWindow
  66: SetLoadLibraryCallback
  67: winit::platform_impl::platform::window_state::WindowFlags::apply_diff
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\window_state.rs:245
  68: winit::platform_impl::platform::window_state::WindowState::set_window_flags<closure-0>
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\window_state.rs:141
  69: winit::platform_impl::platform::window::{{impl}}::set_visible::{{closure}}
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\window.rs:132
  70: winit::platform_impl::platform::event_loop::EventLoopThreadExecutor::execute_in_thread<closure-0>
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop.rs:414
  71: winit::platform_impl::platform::window::Window::set_visible
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\window.rs:131
  72: winit::window::Window::set_visible
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\window.rs:557
  73: gelatin::window::Window::new
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\gelatin-0.4.0\src\window.rs:141
  74: emulsion::main
             at src\main.rs:106
  75: std::rt::lang_start::{{closure}}<()>
             at C:\Users\ragib\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  76: std::rt::lang_start_internal::{{closure}}
             at /rustc/67100f61e62a86f2bf9e38552ee138e231eddc74\/src\libstd\rt.rs:52
  77: std::panicking::try::do_call
             at /rustc/67100f61e62a86f2bf9e38552ee138e231eddc74\/src\libstd\panicking.rs:296
  78: std::panicking::try
             at /rustc/67100f61e62a86f2bf9e38552ee138e231eddc74\/src\libstd\panicking.rs:273
  79: std::panic::catch_unwind
             at /rustc/67100f61e62a86f2bf9e38552ee138e231eddc74\/src\libstd\panic.rs:394
  80: std::rt::lang_start_internal
             at /rustc/67100f61e62a86f2bf9e38552ee138e231eddc74\/src\libstd\rt.rs:51
  81: std::rt::lang_start<()>
             at C:\Users\ragib\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  82: main
  83: invoke_main
             at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  84: __scrt_common_main_seh
             at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  85: BaseThreadInitThunk
  86: RtlUserThreadStart

===================================================================================================
error: process didn't exit successfully: `target\debug\emulsion.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
</pre>

BTW, it is using a nightly compiler, as you can see. Should I try a stable compiler instead?

**Comment by RagibHasin** [comment]
With stable rustc (1.44.1)

<pre>
$ cargo +stable run
   Compiling emulsion v4.0.0 (D:\Projects\Y 20\Contrib\emulsion)
warning: variable does not need to be mutable
   --> src\picture_widget.rs:590:10
    |
590 |                     let mut borrowed = self.data.borrow_mut();
    |                         ----^^^^^^^^
    |                         |
    |                         help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 10.99s
     Running `target\debug\emulsion.exe`

Panic happened

--
buffering RedrawRequested event
--

Location C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop\runner.rs:110:17

   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.48\src\backtrace\dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized<closure-0>
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.48\src\backtrace\mod.rs:66
   2: backtrace::backtrace::trace<closure-0>
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.48\src\backtrace\mod.rs:53
   3: backtrace::capture::Backtrace::create
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.48\src\capture.rs:164
   4: backtrace::capture::Backtrace::new
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.48\src\capture.rs:128
   5: emulsion::handle_panic::handle_panic
             at src\handle_panic.rs:14
   6: core::ops::function::Fn::call<fn(core::panic::PanicInfo*),(core::panic::PanicInfo*)>
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\libcore\ops\function.rs:72
   7: std::panicking::rust_panic_with_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:515
   8: std::panicking::begin_panic<str*>
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\libstd\panicking.rs:438
   9: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event<()>
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop\runner.rs:110
  10: winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop.rs:102
  11: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop.rs:0
  12: DefSubclassProc
  13: DefSubclassProc
  14: CallWindowProcW
  15: CallWindowProcW
  16: glPushClientAttrib
  17: CallWindowProcW
  18: DispatchMessageW
  19: IsWindowVisible
  20: KiUserCallbackDispatcher
  21: NtUserDispatchMessage
  22: DispatchMessageW
  23: InputFocusMonitorCreate
  24: InputFocusMonitorCreate
  25: TF_Notify
  26: TF_Notify
  27: TF_SendLangBandMsg
  28: <unknown>
  29: DllUnregisterServer
  30: TF_SendLangBandMsg
  31: TF_SendLangBandMsg
  32: TF_SetDefaultRemoteKeyboardLayout
  33: SetInputScopes2
  34: CtfImeProcessCicHotkey
  35: CtfImeProcessCicHotkey
  36: CtfImeAssociateFocus
  37: CtfImeAssociateFocus
  38: CtfImeAssociateFocus
  39: ImmSetActiveContext
  40: GetWindow
  41: GetWindowRgnBox
  42: GetDlgItem
  43: GetDlgItem
  44: CallWindowProcW
  45: DispatchMessageW
  46: IsWindowVisible
  47: KiUserCallbackDispatcher
  48: NtUserMessageCall
  49: GetWindowTextW
  50: GetWindowTextW
  51: CallWindowProcW
  52: CallWindowProcW
  53: DefSubclassProc
  54: DefSubclassProc
  55: DefSubclassProc
  56: DefSubclassProc
  57: CallWindowProcW
  58: CallWindowProcW
  59: glPushClientAttrib
  60: CallWindowProcW
  61: DispatchMessageW
  62: IsWindowVisible
  63: KiUserCallbackDispatcher
  64: NtUserShowWindow
  65: SetLoadLibraryCallback
  66: winit::platform_impl::platform::window_state::WindowFlags::apply_diff
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\window_state.rs:245
  67: winit::platform_impl::platform::event_loop::EventLoopThreadExecutor::execute_in_thread<closure-0>
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\event_loop.rs:414
  68: winit::platform_impl::platform::window::Window::set_visible
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.0\src\platform_impl\windows\window.rs:131
  69: gelatin::window::Window::new
             at C:\Users\ragib\.cargo\registry\src\github.com-1ecc6299db9ec823\gelatin-0.4.0\src\window.rs:141
  70: emulsion::main
             at src\main.rs:106
  71: std::rt::lang_start::{{closure}}<()>
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\libstd\rt.rs:67
  72: std::rt::lang_start_internal::{{closure}}
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\rt.rs:52
  73: std::panicking::try::do_call
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:331
  74: std::panicking::try
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:274
  75: std::panic::catch_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panic.rs:394
  76: std::rt::lang_start_internal
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\rt.rs:51
  77: std::rt::lang_start<()>
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\libstd\rt.rs:67
  78: main
  79: invoke_main
             at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  80: __scrt_common_main_seh
             at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  81: BaseThreadInitThunk
  82: RtlUserThreadStart

===================================================================================================
error: process didn't exit successfully: `target\debug\emulsion.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
</pre>

**Comment by RagibHasin** [comment]
BTW, debugging with VSCode + CodeLLDB works fine.

**Comment by ArturKovacs** [comment]
> BTW, debugging with VSCode + CodeLLDB works fine.

Thanks for the tip! I'll try that next time I need to debug.
