### ISSUE TITLE
Change panning to left click

### ISSUE THREAD

**Issue by retrotails** [ArturKovacs/emulsion#130]
right click is inconvenient on my trackball and most viewers seem to use left-click pan. I'm not sure how you'd want to do it, but the most basic combining the left/right click in picture_widget.rs seems to work fine for me. configurable mouse buttons (and maybe configurable double-press for any key/button) would also work but I can see how that'd be a challenge.
```rust
MouseButton::Left => {
	let mut borrowed = self.data.borrow_mut();
	if state == ElementState::Pressed {
		borrowed.click = borrowed.hover;
		borrowed.panning = borrowed.hover;
		if borrowed.hover {
			let now = Instant::now();
			let duration_since_last_click =
				now.duration_since(borrowed.last_click_time);
			borrowed.last_click_time = now;
			if duration_since_last_click < Duration::from_millis(250) {
				match borrowed.window.upgrade() {
					Some(window) => {
						let fullscreen = !window.fullscreen();
						window.set_fullscreen(fullscreen);
						borrowed.bottom_bar.set_visible(!fullscreen);
					}
					None => unreachable!(),
				}
			}
		}
	} else {
		borrowed.panning = false;
		borrowed.click = false;
	}
	borrowed.render_validity.invalidate();
}
```
the only thing I might add is not triggering the double-click action when you pan, so quick short pans don't toggle full screen, but honestly it's hard to accidentally trigger that and it might make the double-tap much harder on a touch screen.

**Comment by ArturKovacs** [comment]
The panning input should be changed to left click and reserve right click for context-menu. I edited the title according to this.

Of course it's going to be strange for users to see that right click doesn't pan anymore but when trying to use right click to pan, a text should appear saying that left click must be used for panning.

I'll implement this.
