### ISSUE TITLE
Some images appear with incorrect orientation

### ISSUE THREAD

**Issue by ArturKovacs** [ArturKovacs/emulsion#134]
For example the jpeg image in the following package will appear with incorrect rotation in Emulsion but it appears correctly in the Windows Photos app.

I'm assuming that the exif data stores the proper orientation in this case which could be read in the image loader and sent to the image cahce along with the pixel data; then when it comes to rendering the image the transformation matrix for the verices should include this rotation.

[00000IMG_00000_BURST20190818114807752_COVER.zip](https://github.com/ArturKovacs/emulsion/files/4912030/00000IMG_00000_BURST20190818114807752_COVER.zip)

**Comment by Aloso** [comment]
Related issue: https://github.com/image-rs/image/issues/1259. `image` returns an error when trying to parse some rotated images. However, that's not the case here, so this bug should be easier to fix.

I experimented with rotating/flipping images a little while ago: https://github.com/Aloso/emulsion/blob/rotate-flip/src/image_cache/transforms.rs.

To find out if an image must be rotated/flipped, we'd have to read the EXIF data. Alternatively, we could add keyboard shortcuts to rotate/flip an image.

**Comment by ArturKovacs** [comment]
> To find out if an image must be rotated/flipped, we'd have to read the EXIF data. 

Yep, agreed.

> Alternatively, we could add keyboard shortcuts to rotate/flip an image.

I understand this is tempting to implement. I wrote about this in a reddit comment from which I pasted the relevant parts below.

### "

Allowing to rotate the image is one of those features that's a bit tricky to decide if it's a good idea to have.

As far as I know, most image viewers allow you to rotate the image and if you do, either the metadata gets updated or the pixels themselves are re-written. So the expectation is that if I rotate the image, it should stay rotated even if I open it on a different computer. Following this line of thinking, allowing to rotate the image but not storing that information, may invoke a feeling of a feature missing or maybe a bug being present. Whereas not being able to rotate the image at all cleary communicates that it's not something that one should expect Emulsion to do.

Furthermore the reason why Emulsion tries to stick to being just a viewer with no editing capabilities is because adding editing features is a slippery slope in my opinion which works against maintaining minialism.

### "

Source: https://www.reddit.com/r/rust/comments/heyr7j/view_apng_with_emulsion_and_image/fwegxdn/?context=3
