### ISSUE TITLE
Add AVIF support for Windows

### ISSUE THREAD

**Issue by ArturKovacs** [ArturKovacs/emulsion#135]
As discussed in #116 `libavif-rs` `v0.3` supports Windows. Emulsion should use it and should support opening avif files on windows and the optional cargo feature enabling avif support should either be removed or it should be made default.

**Comment by paolobarbolini** [comment]
Enabling the `avif` feature by default doesn't seem a good option, especially on Windows where [installing NASM](https://bugzilla.nasm.us/show_bug.cgi?id=3392224) isn't as straight forward as just letting some package manager install all of the external dependencies. Just a thought, I'm not using Windows anyway

**Comment by ArturKovacs** [comment]
I see, you are right it shouldn't be default then, but it should be part of the autmated build that's done when pushing a release tag.

**Comment by ArturKovacs** [comment]
Resolved at 7b37051aa4f275f3d5d357cd2d0e548042dc6b2f
