### ISSUE TITLE
"Error occurred while loading file" infinite loop

### ISSUE THREAD

**Issue by Shnatsel** [ArturKovacs/emulsion#140]
When opening the attached image, emulsion hangs and prints the following line to stderr over and over:

```
Request #4366: Error occurred while loading file "test.png"
    Unknown image format
```

Meanwhile image viewers based on gdk-pixbuf open the file fine. So there are two problems here: image not being supported and the error triggering an infinite loop.

I have run `image` on this corpus earlier without any issues, so this is likely an issue with one of the new additions like exif.

**Comment by Shnatsel** [comment]
![test](https://user-images.githubusercontent.com/291257/89944121-9891a480-dc1f-11ea-852f-72c182ed11e6.png)

**Comment by ArturKovacs** [comment]
It should be fixed now. Thanks for reporting!
