### ISSUE TITLE
Add more cfg options

### ISSUE THREAD

**Issue by ArturKovacs** [ArturKovacs/emulsion#147]
As written in #144 

> I would love to have more customizability. Namely in "cfg.toml" file values like "start_fullscreen", "hide_statusbar" (or whatever it is called), "remember_last_session" (to disable "cache.toml" or just ignore values stored there) paired with values for default position and size would be awesome

I suggest the following names

- `start_fullscreen` - If true, Emulsion starts in fullscreen (default: false)
- `show_bottom_bar` - If true, the ui bar with the buttons at the bottom is show, otherwise it's hidden (default: true)
- `use_last_window_area` - If true, the window starts with the same transformation as the previously closed window (default: true)

**Comment by akimdi** [comment]
I'm really looking forward to these options

**Comment by ArturKovacs** [comment]
Thanks for leaving a comment, it helps me prioritize things. I'll try to implement these reasonably soonish
