### ISSUE TITLE
Panic when unable to write config file

### ISSUE THREAD

**Issue by wezm** [ArturKovacs/emulsion#15]
Hi, first off thanks for building this. It seems like just the thing to replace `sxiv` for me, which doesn't seem to support my HiDPI desktop properly.

I built an [AUR package](https://wiki.archlinux.org/index.php/Arch_User_Repository) for `emulsion` (not yet published due to this issue), which results in the binary being installed in `/usr/bin/emulsion`.

I ran `emulsion` then pressed `Esc` to quit and encountered this panic. It seems strange to me that `emulsion` would try to write a config file into the system `/usr/bin` directory. This should probably be written into [XDG_CONFIG_DIR](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) (via a crate like [directories](https://crates.io/crates/directories)).

**OS:** Arch Linux

```
Found latest version tag v1.9
Current version is '1.9.0'
Parsed latest version is '1.9.0'

Panic happened

--
called `Result::unwrap()` on an `Err` value: "Could not write to config file \"/usr/bin/cfg.toml\""
--

Location src/main.rs:309:9

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: __libc_start_main
  19: <unknown>

===================================================================================================

Panic happened

--
Could not write panic to file.: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
--

Location src/handle_panic.rs:40:5

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: __libc_start_main
  24: <unknown>

===================================================================================================
thread panicked while processing panic. aborting.
[1]    3407264 illegal hardware instruction (core dumped)  emulsion
```

**Comment by tpoliaw** [comment]
I installed via cargo and have just checked and it's written a config file (appears to be window dimensions?) to `~/.cargo/bin/`. There was no panic for me given I have write permissions but I second the idea of using standard config directories.

**Comment by ArturKovacs** [comment]
I do agree with @wezm that the config file shouldn't go to the bin directory. I think using `directories`  as suggested, would be an optimal solution.

**Comment by ArturKovacs** [comment]
@wezm please see if the latest master still has this issue for you.

(Fix applied by 519d43796a9dab34b75820858ba7256eba88457d)

**Comment by ArturKovacs** [comment]
I just realized that this probaly affects the panic.txt file just as well so now that will be placed to a hopefully more appropriate location. More specificaly the directory that `ProjectDirs::data_local_dir` of the directories crate returns.

**Comment by wezm** [comment]
Great, thanks @ArturKovacs. I have tested master and it seems to do the right thing now :+1:

**Comment by ArturKovacs** [comment]
I'm glad. 🙂 Closing this as solved.
