### ISSUE TITLE
Is there a way to use emulsion to set wallpaper/backgrounds?

### ISSUE THREAD

**Issue by cjwyett** [ArturKovacs/emulsion#157]
Does something along the lines of `feh --bg-scale` exist?

P.S. Great image viewer! Unfortunately I rarely use it as I only ever view the one image.

**Comment by ArturKovacs** [comment]
Hi 👋

This is not something that's built into emulsion although you can achieve this by setting up a custom command along the lines of

```
[[commands]]
input = ["alt+d"]
program = "feh"
args = ["--bg-scale", "${img}"]
```

I'm not familiar with feh so this might not work. In any case you can find out more about custom commands at
https://arturkovacs.github.io/emulsion-website/custom-commands.html

I'm not sure if this should be supported natively however. This to me seems like something that maybe 5% or 10% users would use. And even for them there's almost always a just-as-easy alternative, by using their system setting to set the background. But I'm not "most users" so arguments are welcome.

There are currently two factors that limit the amount of user initiated actions supported out-of-the-box.

1, The time it takes to develop them
2, The space each row takes up from the Info screen.

The second one is a bit silly but IF every supported input should be listed there and IF that screen should fit on every user's display, then the maximum number user initiated actions is limited. Maybe not all input should be listed there, only the important ones, having a line at the end saying, that a complete list can be found on the website. I guess I'll have to think about this.

**Comment by ArturKovacs** [comment]
Considering that this issue itself was a question, I'll close this as it seems that the question got answered.

If there's a need to allow setting the wallpaper using emulsion, feel free to open a feature request. Just to avoid confusion, I'm not particularly inclined to implement this unless there are indications that this is generaly important for users. Otherwise PRs are always welcome.
