### ISSUE TITLE
How do I zoom in on a keystroke?

### ISSUE THREAD

**Issue by akimdi** [ArturKovacs/emulsion#158]
I wrote the following lines in the config file but it doesn't work for some reason
[https://github.com/akimdi/emulsion/blob/master/cfg.toml#L10](https://github.com/akimdi/emulsion/blob/master/cfg.toml#L10)

**Comment by ArturKovacs** [comment]
Hi. Thanks for your interest.

Currently there's no way to zoom other than scrolling (emulated scroll input should in theory be supported as well). I created #159 to solve this.

**Comment by akimdi** [comment]
Thank you.
