### ISSUE TITLE
Allow zooming and panning to be bound to key inputs

### ISSUE THREAD

**Issue by ArturKovacs** [ArturKovacs/emulsion#159]
Currently the only way to zoom is to scroll and the only way to pan the view is clicking and dragging with the cursor.

The config should allow specifying custom keyboard input for these. Although I think these still shouldn't have a keyboard input by default.

**Comment by akimdi** [comment]
> Although I think these still shouldn't have a keyboard input by default.

Yes by default.
But some users need customization in the config file.
This increases the flexibility of the application.
