### ISSUE TITLE
File associations registration on Windows is incomplete

### ISSUE THREAD

**Issue by nielsmh** [ArturKovacs/emulsion#181]
The way the installer for Windows registers file associations is incomplete, and does not support the Default Programs feature that was introduced in Windows XP SP2. Because of this, Windows 10 might assume the way the installer tries to set file associations is a user-hostile program trying to steal associations without the user's permission, and cause Windows to reset the associations back to whatever they were before.

Documentation on the Default Programs API set: https://docs.microsoft.com/en-us/windows/win32/shell/default-programs

**Comment by ArturKovacs** [comment]
Hey, thanks for bringing attention to this. I'm personally not satisfied with that part of the installer either as it causes weird issues (For example I believe the icons are broken for PNG files associated with emulsion, and this: https://github.com/ArturKovacs/emulsion/commit/a98f39dd70f2a1f582ac30d78c6f5c2386743e61)

I would really appreciate a PR for, this as I'm completely swamped and so I almost definitely won't have time for this in the foreseeable future.
