### ISSUE TITLE
Compilation works even with missing dependencies

### ISSUE THREAD

**Issue by flosse** [ArturKovacs/emulsion#20]
I can successfully compile emulsion even if `libX11` is not available (as long as the OpenSSL dependency is satisfied).
I think it should fail because the execution panics:
```sh
./target/release/emulsion

Panic happened

--
Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libX11.so.6: cannot open shared object file: No such file or directory); opening library failed (libX11.so: cannot open shared object file: No such file or directory)" })
--

Location /home/mk/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.0/src/platform_impl/linux/mod.rs:569:9

   0: emulsion::handle_panic::handle_panic
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
   2: std::panicking::begin_panic
   3: winit::platform_impl::platform::EventLoop<T>::new
   4: winit::event_loop::EventLoop<()>::new
   5: gelatin::application::Application::new
   6: emulsion::main
   7: std::rt::lang_start::{{closure}}
   8: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
      std::panicking::try::do_call
             at src/libstd/panicking.rs:305
   9: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  10: std::panicking::try
             at src/libstd/panicking.rs:281
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  11: main
  12: __libc_start_main
  13: _start
```
*Edit:* I'm running Linux (NixOS)

**Comment by ArturKovacs** [comment]
Yeah that's right, this should fail at building, optimally. Correct me if I'm wrong but this seems like a very rare scenario and that many of the other issues that are currently open are more impactful considering the majority of users.

**Comment by flosse** [comment]
> Correct me if I'm wrong but this seems like a very rare scenario and that many of the other issues that are currently open are more impactful considering the majority of users.

absolutely! This issue can be tagged as low-prio or so :)

**Comment by ArturKovacs** [comment]
I added an example nix expression to the`nix-example` folder which when built using `nix-build` should produce a working emulsion executable. There isn't any guarantee for which version of emulsion this executable be. In fact currently it's directly referring to a commit which doesn't have an associated version. Hence, it's just an example.

I believe that the problem that this issue stems from is that it's hard to get a working emulsion executable with a nix expression. Now that there is a nix expression which does that, I believe it's sensible to close this issue.
