### ISSUE TITLE
Feat: custom commands on path

### ISSUE THREAD

**Issue by yory8** [ArturKovacs/emulsion#22]
A way to bind custom shell commands to custom keybindings, operating on the path of current image.
So for example, binding `mv %s ~/.Trash/` to `Shift+Del` and so on.

**Comment by ArturKovacs** [comment]
I really like this idea. Although it's definitely not for everybody, it should not have a negative impact on any other use case.

FYI pressing the delete key while an image is open, said image will be put into the OS Trash folder on all supported platforms. This should be added to the info screen which I'll do later.

**Comment by rslife** [comment]
> FYI pressing the delete key while an image is open, said image will be put into the OS Trash folder on all supported platforms. This should be added to the info screen which I'll do later.

`qiv` had a trash feature (moving images to `./.qiv-trash/` folder) and I hated it with heart, but they provided a `-R/--readonly` option which made the situation tolerable.

`pqiv` (which is my current image viewer of choice), in what I presume was an attempt to correct that qiv behavior, adjusted the feature to hard-linking images to the folder `./.pqiv-select` instead of moving them, but no explicit `--readonly` option was provided.

I strongly suggest that emulsion stay read-only with the default keybindings. And if that does not end up being the case, an explicit read-only option should IMHO be provided.

**Comment by ArturKovacs** [comment]
I'm curious what made you hate that feature so much. Is it the fact that you might accidentally press delete and delete something you didn't want to? Regardless, adding a command line option for read-only mode shouldn't be difficult.

**Comment by yory8** [comment]
Thanks. Other uses of this feature besides handling trash would be allowing users to implement stuff like "open terminal in this image's folder", "save a copy of this image in home", "open with gimp", etc. Basically all that stuff that can be useful to someone but is not worth being built-in because each user as their own special needs etc.

**Comment by rslife** [comment]
> Is it the fact that you might accidentally press delete and delete something you didn't want to?

Exactly. I was *using* the feature without knowing it existed. The default keybindings in `qiv` for moving images to the trash folder are `d/D/del`. So I was hitting `d` accidentally and images where disappearing ;) So one day I find a `.qiv-trash` folder. Then I run `find / -type d -name '.qiv-trash'` and find a lot of matches.

Looking back now, I think if they went with `del` only as a keybinding, I probably would have never hit this annoyance.

It is also the general principle of it. A *viewer* (vs. an editor or a manager) not being read-only by default is unexpected (and potentially dangerous if some unrecoverable files get accidentally lost somehow).

----

**Correction from my last comment**: `qiv` also has a select feature (not disabled by `--readonly`), so `pqiv` only removed the trash feature while keeping the select feature.

**Comment by ArturKovacs** [comment]
@rslife Yeah binding delete to the `d` key is a bit cheeky though. Would you mind creating a feature request for the readonly mode?

@yory8 Alright. But before this gets implemented I have to ask what makes you suggest using `%s` as a substitute for the path? Where does this notation come from? Could there be a better one for example `${file}` and maybe `${folder}` for the parent folder? I don't have a horse in this race I just want to make sure we choose something we'll be happy with down the line.

**Comment by yory8** [comment]
@ArturKovacs it comes from the ranger file manager (where it means "the Selected file"), but it was just an example.
`${file}` and `${folder}` are much better for this use case: in ranger, it must be short because it's typed by the user every time, whereas here we write it only once in the config.

**Comment by rslife** [comment]
> Would you mind creating a feature request for the readonly mode?

I was about to send you a PR adding `no_trash` option to `Configuration`. But that's not required anymore after c7416795cadfc87f54c47e5c8ecd7d309f01c725. This does the trick:

```
[bindings]
img_del = []
```

**Comment by yory8** [comment]
Thanks!
