### ISSUE TITLE
Add animated gif support

### ISSUE THREAD

**Issue by ArturKovacs** [ArturKovacs/emulsion#27]
Currently only the first frame is displayed from animated gif files. Would be great if emulsion could play the animation.

**Comment by musoke** [comment]
This would be great!

**Comment by ArturKovacs** [comment]
I'm currently working on this.

**Comment by tuncer** [comment]
Any thoughts on including playback control?

**Comment by ArturKovacs** [comment]
Yeah I considered it. To me personally it would make sense to allow pausing and stepping by frame and such but I'm not yet sure what the user interaction would be so that it's relatively intuitive. I'm thinking about somehow reusing the the playback shortcut to pause and play the gif and the next/prev image to step to the next/prev frame. Of course it should be done in a way that makes it easy to understand when those actions target the current gif instead of the entire folder.

**Comment by tuncer** [comment]
I can see two implementations. (1) One would be adding animation-specific bindings to control playback, and (2) another would be overriding normal bindings when an animated file is displayed, combined with a `end-animation` binding. Not sure which one is more intuitive, but right now I'd say (1) is less surprising.

Should there be on-screen controls for GIF playback?
