### ISSUE TITLE
Emulsion overwrites an invalid cfg file

### ISSUE THREAD

**Issue by ArturKovacs** [ArturKovacs/emulsion#29]
When a cfg file has invalid content, emulsion will load the default configuration which will be written to disk when exiting, overwriting the existing cfg.

To avoid this problem altogether, have two separate files instead. One containing data that's modified by emulsion, like window size and position. The other one containing data that is not modified by emulsion like key-bindings.

**Comment by tuncer** [comment]
This is a good idea. Does anyone know what the convention is? I mean, would ephemeral data like last window size/position go in XDG cache or config directory?
