### ISSUE TITLE
Add CBZ/CBR support.

### ISSUE THREAD

**Issue by ArturKovacs** [ArturKovacs/emulsion#3]
I'm not yet sure how would the user switch between comic books and images within a single cb but this may be fairly straingthforward to implement and shouldn't be intrusive for those who don't use this feature.

**Comment by juan-riveros** [comment]
Yes please? I'd love to have this feature since that's my main use case for a simple image viewer.

**Comment by Aloso** [comment]
It seems that CBR files are much more common than CBZ files.

I got basic CBZ support working, using the `zip` crate. For CBR support, the best option seems to be the `unrar` crate, which contains bindings to to a C++ library.

To navigate the comic, we'll need two new key bindings, e.g. <kbd>Ctrl+ArrowLeft</kbd> and <kbd>Ctrl+ArrowRight</kbd>. The page should also be displayed in the title, e.g. `Comics/MyComic.cbz [Page 3/24]`.

**Comment by ArturKovacs** [comment]
I also thought of having a separate keybinding for stepping just within the comic book. But for those who would read many comic books with Emulsion it would be annoying to have to keep in mind which button you need to press to avoid accidentally steping to a different image or comic book in the folder.

Therefore a I propose that we treat cbr and cbz files similar to a folder. When you step on them you get a preview and then pressing for example <kbd>Alt+E</kbd> would "Enter" the comic book treating it as a folder of images so that <kbd>ArrowRight</kbd> steps on the next page. Triggering "Enter" again would leave the comic book and go back to its parent directory.

**Comment by Aloso** [comment]
I found the `compress-tools` crate that can read many archive types, including ZIP, TAR and RAR. Unfortunately it lacks a feature to list the files in an archive, so I [filed an issue](https://github.com/OSSystems/compress-tools-rs/issues/22). The crate authors want to add the feature soon.

**Comment by ArturKovacs** [comment]
Based on my experience Emulsion is not suitable for reading comfortably reading comic books, due to how it handles the "camera". See my comment at https://github.com/ArturKovacs/emulsion/pull/169#issuecomment-761867082

What would be the reason that you'd like to use Emulsion for reading comic books instead of let's say Evince or Calibre? It seems that those two are just objectively better for this usage.

I really thought that this is an important feature and that it was going to be a nice to have it, but after gathering more knowledge about the topic I'm now considering closing this issue with "won't fix".
