### ISSUE TITLE
MacOS maintainer wanted

### ISSUE THREAD

**Issue by ArturKovacs** [ArturKovacs/emulsion#33]
At this point I mainly use Windows as a development platform but I test and can investigate bug reports for Linux (mostly Ubuntu). However I can't do these for Macs as I don't own one.

I think it's important that emulsion's features are all available on Mac OS as well so I'm looking for someone who could make sure before a build is published that things work as they should.

**Comment by danechambers** [comment]
I can lend a hand if you would like. I have a 2017 mbp:
<img width="486" alt="Screen Shot 2020-04-26 at 12 33 43 AM" src="https://user-images.githubusercontent.com/2801346/80300966-cb3d8d00-8755-11ea-9897-1a859f9ffc54.png">
Are there any other requirements you would need for help with MacOS maintenance other than testing if the things still work? I'm still working my way through the rust book and I wouldn't call myself an expert in the language just yet.

**Comment by ArturKovacs** [comment]
> Are there any other requirements you would need for help with MacOS maintenance other than testing if the things still work?

Most importantly testing but I would really like to provide some kind of installable package for MacOS just as with Windows. And of course helping with bug reports is always appreciated but nothing is required.

You can find my email address at my profile page. Please write me so we can find find out what instant messaging solution we should use to coordinate this.

**Comment by girardof** [comment]
I tried to compile emulsion earlier today on a osx (v10.14.6) and got the following error :
`cargo build --release`
```
Compiling bytes v0.5.4
error: `core::slice::<impl [T]>::len` is not yet stable as a const fn
   --> /Users/girardo/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.5.4/src/bytes.rs:130:18
    |
130 |             len: bytes.len(),
    |                  ^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `bytes`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
Any idea of what I'm doing wrong ?

**Comment by girardof** [comment]
My bad, Rust needed to be updated. Would you like me to provide you the compiled library for osx ?

**Comment by ArturKovacs** [comment]
We agreed with @danechambers that he'll provide a dmg package for the next version (which is probably going to be released this Sunday the latest). I'm also thinking about setting up a Github Action that creates a dmg on every tag on a specific branch or maybe every commit on a branch. 

With that said, for now, just to keep the logistics as simple as possible let's say that this is taken by @danechambers unless he changes his mind.

**Comment by girardof** [comment]
I went ahead with the PR before waiting for you answer sorry for that.

**Comment by ArturKovacs** [comment]
No need to apologize :)

**Comment by ArturKovacs** [comment]
Unfortunately @danechambers cannot continue with this so I'm looking for help again.

I wrote an Action workflow that creates a release on github and then builds the windows installer and uploads it to that release. It can be found [here](https://github.com/ArturKovacs/emulsion/blob/master/.github/workflows/release-packages.yml). I need someone to add a `macos` job to this which builds the executable with all features enabled and then creates an appropriate distributable package for the MacOS and uploads it as an attachment to the same release.

@girardof Would you be interested in this?

**Comment by girardof** [comment]
Sure, I will have a look at it 🙂

**Comment by ArturKovacs** [comment]
@girardof Let me know if I can help in any way. I think that making a shell script locally that creates a distributable package would be the first step and then once that's done you invoke that script in the GitHub Actions workflow and surround it with all the necesary stuf for it to work within Actions.

Also feel free to write me an email and we can discuss how this could be done.

**Comment by girardof** [comment]
@ArturKovacs I had a look at it yesterday but as I'm not familiar with Github actions it took me some time to understand the syntax. 
The only problem remaining I have now is when uploading the assets to the release branch.  Let me have a second look this evening and I will create a PR soon 😃.
