### ISSUE TITLE
Emulsion on `master` branch says "A new version is available"

### ISSUE THREAD

**Issue by Aloso** [ArturKovacs/emulsion#39]
This is displayed on the info screen:

![Screenshot_20200426_225405](https://user-images.githubusercontent.com/15658558/80319515-e3261700-8810-11ea-86f9-af0e84690608.png)

This is printed in the shell:

```
Found latest version tag v1.9
Current version is '2.0.0'
Parsed latest version is '1.9.0'
```

It would be nice if this is only displayed if the current version is older than the parsed latest version.

**Comment by ArturKovacs** [comment]
This should be pretty straightforward. Wanna have a go at this? :)

**Comment by Aloso** [comment]
@ArturKovacs Yes, I'll give it a go.

**Comment by Aloso** [comment]
I'm finished, just checking if it works. However, I'm wondering if it would be better to use the [semver](https://docs.rs/semver/0.9.0/semver/) crate for parsing and comparing versions?

**Comment by ArturKovacs** [comment]
Thank you. I don't think we should use the semver crate for this. We should consider using it again, if we'll deal with more complictaed version comparisons like caret requirements and wildcard requirements and such.
