### ISSUE TITLE
Which license is this project using?

### ISSUE THREAD

**Issue by bbigras** [ArturKovacs/emulsion#4]
Github usually show the license but not for this project. I need to know the exact license to package it for a Linux distribution.

some project:
![image](https://user-images.githubusercontent.com/24027/79891456-01ce7d00-83cf-11ea-808f-2412d574ac37.png)

emulsion:
![image](https://user-images.githubusercontent.com/24027/79891564-27f41d00-83cf-11ea-8a57-161df111966c.png)

EDIT: I read the license file but couldn't determine which one it is (gpl, isc, mit...).

**Comment by TomasGutierrez0** [comment]
It shouldn't matter if its GPL, MIT or any other license, its a license that lets you know what you can or can't do. Looks like MIT though

**Comment by ArturKovacs** [comment]
Thanks for pointing that out. It's MIT by the way but this should be fixed by b7b6b27347f5c75d5bc3631bdf1e7e9b25333150

**Comment by ArturKovacs** [comment]
I don't know why it's still showing "View licenese" instead of MIT because I copied the text as-is from https://choosealicense.com/licenses/mit/

**Comment by bbigras** [comment]
Thank you very much.
