### ISSUE TITLE
Make checking for updates optional

### ISSUE THREAD

**Issue by Aloso** [ArturKovacs/emulsion#41]
Add a property to the configuration file to disable checking for updates.

Also, don't check for updates if the last check was less than 10 min ago, and handle network errors (e.g. due to no connection) gracefully.

I'd like to implement this if that's okay.

**Comment by ArturKovacs** [comment]
@Aloso it's yours. I'm wondering though if it would be better to address #29 first especially because of the last update time within X minutes stuff.

**Comment by Aloso** [comment]
There's one issue I discovered: The `config` value isn't `Send` because it contains a `RefCell`. However, checking for updates happens in a separate thread.

One possibility would be to store the needed information in `Arc<Atomic{Bool, U64}>` after checking for updates, and only modify `config` in the `application.set_at_exit()` callback. Is there a better solution?

**Comment by ArturKovacs** [comment]
Feel free to make the `Rc<RefCell<...>>` things into `Arc<Mutex<...>>` if needed.

**Comment by ArturKovacs** [comment]
Also feel free to make the update check delay 24 hours instead of 10 minutes.
