### ISSUE TITLE
Leave fullscreen when pressing `Esc` in fullscreen mode

### ISSUE THREAD

**Issue by Aloso** [ArturKovacs/emulsion#45]
When I maximize the window or enter the fullscreen mode and then close the program with <kbd>Escape</kbd>, the next time I open a picture, the window covers the entire screen.

Instead, it should remember the size of the window when it wasn't maximized or in fullscreen mode. It would also be nice if emulsion remembered whether the window was maximized, in fullscreen mode or normal.

**Comment by ArturKovacs** [comment]
In my opinion the window should just leave full-screen and stop there when pressing <kbd>Escape</kbd> in full-screen mode. I think that would solve this issue.

**Comment by ArturKovacs** [comment]
@Aloso I'd like to have this in the next release, which I'm hoping to do early this weekend. Would you like to take this and get this bad boy done quick?

**Comment by Aloso** [comment]
Yes, I'll implement it.

**Comment by Aloso** [comment]
@ArturKovacs It seems like there's no simple way to exit the application outside of gelatin. I tried to add an `exit()` method to `Application`, but that caused problems with the borrow checker. My current solution is rather ugly.
