### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by omac777** [ArturKovacs/emulsion#5]
The same error appears both in archlinux and windows 10:

```
$ cat panic.txt


--
called `Result::unwrap()` on an `Err` value: IoError(Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." })
--

Location src\main.rs:55:15

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: emulsion::handle_panic::handle_panic
   3: std::panicking::rust_panic_with_hook
             at /rustc/96bb8b31c81dc2394317f2f083c3acf8087efea1\/src\libstd\panicking.rs:474
   4: std::panicking::begin_panic_handler
             at /rustc/96bb8b31c81dc2394317f2f083c3acf8087efea1\/src\libstd\panicking.rs:378
   5: core::panicking::panic_fmt
             at /rustc/96bb8b31c81dc2394317f2f083c3acf8087efea1\/src\libcore\panicking.rs:85
   6: core::option::expect_none_failed
             at /rustc/96bb8b31c81dc2394317f2f083c3acf8087efea1\/src\libcore\option.rs:1211
   7: alloc::slice::merge_sort
   8: <T as core::any::Any>::type_id
   9: std::rt::lang_start_internal::{{closure}}
             at /rustc/96bb8b31c81dc2394317f2f083c3acf8087efea1\/src\libstd\rt.rs:52
  10: std::panicking::try::do_call<closure-0,i32>
             at /rustc/96bb8b31c81dc2394317f2f083c3acf8087efea1\/src\libstd\panicking.rs:303
  11: panic_unwind::__rust_maybe_catch_panic
             at /rustc/96bb8b31c81dc2394317f2f083c3acf8087efea1\/src\libpanic_unwind\lib.rs:86
  12: std::panicking::try
             at /rustc/96bb8b31c81dc2394317f2f083c3acf8087efea1\/src\libstd\panicking.rs:281
  13: std::panic::catch_unwind
             at /rustc/96bb8b31c81dc2394317f2f083c3acf8087efea1\/src\libstd\panic.rs:394
  14: std::rt::lang_start_internal
             at /rustc/96bb8b31c81dc2394317f2f083c3acf8087efea1\/src\libstd\rt.rs:51
  15: main
  16: invoke_main
             at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  17: __scrt_common_main_seh
             at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  18: BaseThreadInitThunk
  19: RtlUserThreadStart

```

**Comment by ArturKovacs** [comment]
Yeah It's because I got a bit too excited and rushed through the "publishing on crates.io" documentation and forgot to make sure that some vital graphical elements are included. I'm working on it

**Comment by rslife** [comment]
You can just use [`include_bytes!`](https://doc.rust-lang.org/nightly/std/macro.include_bytes.html).

**Comment by rslife** [comment]
[Quick patch](https://gist.github.com/rslife/b28d0d2954d32875913d10c088d8e847) that allows running emulsion without external resource files.

(I'm not a fan of unwraps, especially in [library code](https://github.com/ArturKovacs/emulsion/blob/e57f4af5190c8d1675a879e19a73ea27294c606d/subcrates/gelatin/src/window.rs#L378)).

**Comment by ArturKovacs** [comment]
Yes, I'm about to publish the new emulsion as well that uses this new gelatin.

About the unwrap, you are right I'm not a fan either I'll change that so that the error is progagated. But I really doubt that gelatin has any other use case than emulsion. Which is the reason there are probably quite some more unclean solutions like that which only make sense in the context of emulsion.

**Comment by omac777** [comment]
I just built with the fix above, but now it hangs on the usage dialog.
I see the click/drag area cursor at the bottom.  I try to click anywhere on that dialog and it displays a "quit or wait" dialog in archlinux.  I try to press any key suggested by usage dialog and it displays the "quit or wait" dialog again.

There is no panic.txt file anymore, but I see no diagnostic debug messages in the terminal to hint to where the issue resides.

**Comment by ArturKovacs** [comment]
I just published the new version of emulsion. Try to `cargo install emulsion` now and see what happens this time. It did work on an ubuntu for me before publishing but let's see.

**Comment by omac777** [comment]
I attached a screenshot showing the following with the "quit or wait dialog"
```
cargo install emulsion
cd /home/david/Pictures/
emulsion 
Found latest version tag v1.9
Current version is '1.9.0'
Parsed latest version is '1.9.0'
Killed
```
![emulsionQuitOrWait](https://user-images.githubusercontent.com/3756368/79912162-96e16e00-83ef-11ea-8006-5c8604ebc817.png)

**Comment by ArturKovacs** [comment]
Well that's really unfortunate. If I download the latest archlinux from its official homepage will it be the same as what you are running? Because I'd like to install a VM to see what's going on. Also I'll be able to do this tomorrow the soonest.

**Comment by omac777** [comment]
The latest archlinux should produce the above hang and display the "quit or wait" dialog since I did an os update via "pacman -Syuu" this morning.

So I did try v1.9 windows installer on windows 8.  I behaved well, but I needed to learn to drag a picture into the emulsion window and then it displays all pictures in the same folder.  Knowing this information, I went back to archlinux and dragged a picture file into emulsion, but nothing happened same hang "quit or wait" dialog.

**Comment by omac777** [comment]
Change request, please provide CLI support to display pics for directory passed at cli invocation.
i.e.
```
emulsion /home/david/Pictures/ &
```

**Comment by rslife** [comment]
I'm an Archlinux user too. No problems here. And the message in the screenshot is from the specific Desktop Environment/Window manager running.

@omac777 
* Have you tried to actuall wait?
* You need to pass an image from the dir as an argument (yes, that's not ideal, but not related to this issue).

**Comment by omac777** [comment]
One other change request, it should display pictures within subfolders of /home/david/Pictures/ with better granularity as to controlling the sort order of the subfolders.

I believe you did use DJV Viewer for inspiration.  Emulsion does seem similar:
https://darbyjohnston.github.io/DJV/index.html

**Comment by omac777** [comment]
> I'm an Archlinux user too. No problems here. And the message in the screenshot is from the specific Desktop Environment/Window manager running.
> 
> @omac777
> 
>     * Have you tried to actuall wait?
> 
>     * You need to pass an image from the dir as an argument (yes, that's not ideal, but not related to this issue).

Yes, I typically am patient and would wait up to 10 mins for my os to boot and display the gnome desktop.  I waited 2 mins for some image to display, but nothing in archlinux.

**Comment by ArturKovacs** [comment]
@omac777 I'm very happy that you are willing to share your thoughts on Emlusion that's exactly what inspires me but the requests you made are completely unrelated to this issue which seems to be solved according to @rslife 's feedback. Therefore I'm closing this now but feel free to add more comments here relating to the issue if you find out more so I can consider reopening it, or feel free to open new issues for feature requests.

I haven't heard of DJV before but it looks absolutely sleek
