### ISSUE TITLE
Big, convoluted main function

### ISSUE THREAD

**Issue by Aloso** [ArturKovacs/emulsion#50]
The `main` function is so huge that I consider it a maintenance burden. It contains many cloned variables, some of which shadow each other, which makes the code hard to understand.

There are a few possibilities to refactor it into smaller bits and make it easier to understand:

### Helper functions

<details>
<summary>Example</summary>

```rust
fn main() {
    ...
    let moon_img = Rc::new(Picture::from_encoded_bytes(include_bytes!("../resource/moon.png")));
    ...
    let theme_button = Rc::new(Button::new());
    theme_button.set_margin_top(5.0);
    theme_button.set_margin_left(28.0);
    theme_button.set_margin_right(4.0);
    theme_button.set_height(Length::Fixed(24.0));
    theme_button.set_width(Length::Fixed(24.0));
    theme_button.set_horizontal_align(Alignment::Center);
    theme_button.set_icon(Some(moon_img.clone()));
    ...
}
```

Becomes

```rust
fn main() {
    ...
    let moon_img = Rc::new(Picture::from_encoded_bytes(include_bytes!("../resource/moon.png")));
    ...
    let theme_button = make_theme_button(moon_img.clone());
    ...
}

fn make_theme_button(icon: Rc<Picture>) -> Rc<Button> {
    let theme_button = Rc::new(Button::new());
    theme_button.set_margin_top(5.0);
    theme_button.set_margin_left(28.0);
    theme_button.set_margin_right(4.0);
    theme_button.set_height(Length::Fixed(24.0));
    theme_button.set_width(Length::Fixed(24.0));
    theme_button.set_horizontal_align(Alignment::Center);
    theme_button.set_icon(Some(icon));
    theme_button
}
```

</details>

### Blocks

Blocks don't make the function smaller, but by moving variables into smaller blocks, it gets easier to understand. Also, when cloning an `Rc<_>` variable in a block, it can shadow the original variable, since it is dropped at the end:

<details>
<summary>Example</summary>

```rust
fn main() {
    ...
    let update_available_clone = update_available.clone();
    let help_screen_clone = help_screen.clone();
    let update_notification_clone = update_notification.clone();
    update_notification
        .set_visible(help_visible.get() && update_available_clone.load(Ordering::SeqCst));
    help_button.set_on_click(move || {
        help_visible.set(!help_visible.get());
        help_screen_clone.set_visible(help_visible.get());
        update_notification_clone
            .set_visible(help_visible.get() && update_available_clone.load(Ordering::SeqCst));
    });
    ...
}
```

Becomes

```rust
fn main() {
    ...
    {
        let update_available = update_available.clone();
        let help_screen = help_screen.clone();
        let update_notification = update_notification.clone();
        update_notification
            .set_visible(help_visible.get() && update_available.load(Ordering::SeqCst));
        help_button.set_on_click(move || {
            help_visible.set(!help_visible.get());
            help_screen.set_visible(help_visible.get());
            update_notification
                .set_visible(help_visible.get() && update_available.load(Ordering::SeqCst));
        });
    }
    ...
}
```

</details>

### Widgets

Groups of widgets can be encapsulated in wrapper widgets. For example, you could create a widget for the toolbar at the bottom, and a widget for the update notification. This would be more effort, though.

What do you think about these?

**Comment by ArturKovacs** [comment]
I absolutely agree. "Helper functions" and "blocks" would both be very good to have!

Grouping widgets is also a great idea and in some sense the widget builder funtions would already be that. Creating new structs that give higher level management for a group of widgets may be even better for some groups, but I would strongly advise against creating gelatin widgets for this. I would instead just create a custom struct with only the necessary fields and functions and nothing else.

I'm not sure if you can assign yourself but feel free to do so. And one more thing, I'll probably merge a related PR only after the next release. This shouldn't really affect the implementation but just so you know.
