### ISSUE TITLE
Windows installer replaces Adobe Reader's icon.

### ISSUE THREAD

**Issue by ArturKovacs** [ArturKovacs/emulsion#54]
When installing Emulsion on a Windows with Adobe Reader DC already installed, Adobe's icon is replaced by the Emulsion icon.

The installer is built from the nsis script found under the `distribution/windows` folder.

**Comment by ArturKovacs** [comment]
@Aloso, @tuncer would either of you be interested in this?

This is a rather important one in my opinion but I'd like to finish up with the anim gif support first.

**Comment by Aloso** [comment]
Sorry, I'm not that familiar with Windows, I currently don't even have a Windows PC for testing.

**Comment by tuncer** [comment]
I also don't have Windows, but I can see that the NSIS script configures 14 file associations to be handled by Emulsion. Is it really a bug?

https://github.com/ArturKovacs/emulsion/blob/3416385149263363534a9a31e68df9a2ccbd0ec1/distribution/windows/FileAssociation.nsh#L135

https://github.com/ArturKovacs/emulsion/blob/3416385149263363534a9a31e68df9a2ccbd0ec1/distribution/windows/emulsion.nsi#L131-L144

**Comment by tuncer** [comment]
Is it really a bug? The NSIS script configures 14 file associations to be handled by Emulsion:

https://github.com/ArturKovacs/emulsion/blob/3416385149263363534a9a31e68df9a2ccbd0ec1/distribution/windows/FileAssociation.nsh#L135

https://github.com/ArturKovacs/emulsion/blob/3416385149263363534a9a31e68df9a2ccbd0ec1/distribution/windows/emulsion.nsi#L131-L144

**Comment by ArturKovacs** [comment]
@tuncer yes, it really is a bug unfortunately.

**Comment by tuncer** [comment]
I don't have Windows and cannot test. However, to clarify, what should the installer do differently?

**Comment by ArturKovacs** [comment]
@tuncer The installer should install Emulsion in such a way that it doesn't replace other programs' icons.

It seems that this issue particulary with Adobe Reader, comes up in relation to other software as well. The following answer under this stack exchange thread seems to be very insightful. https://superuser.com/a/1328585

According to the anser above, setting the ico file association could be the one that causes Adobe's icon to be replaced. As a workaround I'm going to remove the ico file association from the installer. This is of course not optimal but I prefer this to replacing another program's icon.

**Comment by ArturKovacs** [comment]
I'm closing this as this is sort-of-should-be fixed but as I don't see a better fix happening in the near future it's best to close this for now to avoid cluttering. I will reopen this if it turns out that the fix didn't work or if someone can offer a better fix.

**Comment by tuncer** [comment]
Just to confirm: users want the file association to be something else than Adobe Acrobat, but the icon should be Acrobat's. Correct?

**Comment by ArturKovacs** [comment]
No, in theory the file associations should have nothing to do with this because the issue is that emulsion changes the icon on the shortcut of another program. Imagine that you install emulsion and from then on, Firefox has the emulsion icon as well.

As a sidenote I appreciate that you would like to help but when you keep asking about an issue that you yourself cannot provide assitance with, does not help. Furthermore questions like "Is this really a bug?" doesn't get us closer to the solution either. If you don't understand what the issue is about, describe your interpretation of it so that we can figure out where is the misunderstanding. Don't take this the wrong way, I'm just telling this so that we become more efficient at tackling issues.

**Comment by ArturKovacs** [comment]
I deleted a portion of the discussion between myself and @tuncer as they requested.
