### ISSUE TITLE
Crash on attached pic?

### ISSUE THREAD

**Issue by Geobert** [ArturKovacs/emulsion#6]
When browsing image, emulsion just disapeared on attached picture
[azerty_mac.zip](https://github.com/ArturKovacs/emulsion/files/4512691/azerty_mac.zip)

How can I provide debug log?

**Comment by omac777** [comment]
emulsion just crashed while quickly scrubbing an entire directory of images. When slowly scrubbing, it's ok.

**Comment by ArturKovacs** [comment]
Locate the installation directory and there should be a "panic.txt" somewhere nearby the emulsion executable file. If you pasted the contents I'd be grateful. It may happen that there is no panic.txt file which means that emulsion didn't get notified about the fact that something wen't wrong.

**Comment by Geobert** [comment]
Found it :)

[panic.txt](https://github.com/ArturKovacs/emulsion/files/4514508/panic.txt)

**Comment by ArturKovacs** [comment]
This is an `image-rs` issue but let's leave this open for now.

I posted this at https://github.com/image-rs/jpeg-decoder/issues/148

**Comment by HeroicKatora** [comment]
What's the copyright status on the image? Can we use it as a test case or not?

**Comment by ArturKovacs** [comment]
I found our suspect. https://commons.wikimedia.org/wiki/File:French_notebook.jpg

For preservation purposes, the license is `Creative Commons Attribution-Share Alike 4.0 International`.

**Comment by HeroicKatora** [comment]
You may want to recheck, this should be fixed in latest version of `jpeg-decoder`–`0.1.19`.

**Comment by ArturKovacs** [comment]
@HeroicKatora thanks for the update! I checked it and got an error. I wrote at https://github.com/image-rs/jpeg-decoder/issues/148.
