### ISSUE TITLE
Improve usability in command line

### ISSUE THREAD

**Issue by Aloso** [ArturKovacs/emulsion#64]
Command line users would appreciate the following features:

- [ ] 1. Passing `--version` or `-V` should print the name and version of the program
- [ ] 2. Passing `--help` or `-h` should print the name, version, author, description and usage
- [ ] 3. ~Piping a command to emulsion should work~ &nbsp; see #67 
- [ ] 4. When the program is used incorrectly, an error message should be displayed
- [ ] 5. Errors should be printed to `stderr` instead of `stdout`
- [ ] 6. Debugging info should not be printed, at least in release builds

Some additional details:

- 1\. and 2. could be solved by using `clap`, but implementing it by hand isn't hard either.

- 3\. will allow e.g. `curl http://some_url | emulsion` which is awesome!

    Unfortunately it requires some refactoring to support displaying an image that doesn't correspond to a file in the file system. However, this is required for #12 anyway. 

- 4\. means that an error is displayed if no arguments are provided and emulsion is not used as a pipe, or too many arguments are provided.

- 5\. means that some `println!` statements should be replaced with `eprintln!`

- 6\. means that some `println!` statements should be removed

**Comment by ArturKovacs** [comment]
First of all I like this initiative.

> 3. Piping a command to emulsion should work [...] 3. will allow e.g. `curl http://some_url | emulsion`

In the example you wrote you pipe a potentially random stream of bytes into emulsion's stdin. I'm assuming by "Piping a command" you meant "Piping an image file". As you yourself noted this is a relatively big task and as such should be an issue of its own.

**Comment by ArturKovacs** [comment]
@Aloso I think this would be the best issue for you to work on right now if you are interested.
