### ISSUE TITLE
Mention other installation options

### ISSUE THREAD

**Issue by Aloso** [ArturKovacs/emulsion#73]
The website only provides a download button for windows. It should also link to instructions for installing it on other operating systems.

For Arch Linux, there's an (unofficial?) [AUR package](https://aur.archlinux.org/packages/emulsion) which builds emulsion from source and creates a desktop shortcut.

**Comment by ArturKovacs** [comment]
I absolutely agree. I really want to have macos builds soon, so at least two download buttons should be there. But I'm not really sure what to do about the Linux landscape. My knowledge is limited on it but as far as I know there are maybe three different commonly used package formats. I don't even know what those packages usually contain.

Updates in particular are solved on Windows by just having the installer overwrite the exsisting installation and that's fine. But that's not documented either.

> For Arch Linux, there's an (unofficial?) AUR package

Wow! That's so cool! I don't know who maintains that but it is brilliant :D

**Comment by ArturKovacs** [comment]
@Aloso I updated the [website](https://arturkovacs.github.io/emulsion-website/). Until we have distributable packages for the two other platforms, I don't think that anything better can be done than what I did there. But check and see if it's what you would expect.

**Comment by ArturKovacs** [comment]
I'm closing this for now but as always: feel free to add more comments if this is needed to be reopened.
