### ISSUE TITLE
The hovered image is not always shown.

### ISSUE THREAD

**Issue by ArturKovacs** [ArturKovacs/emulsion#76]
When hovering an image file, Emulsion should display it. If the cursor moves away and the hover gets cancelled Emulsions shows the previously open file.

Currently it seems that even though the `HoveredFile` event is received, the hovered image isn't always shown.

Note: Last time I checked, hovering doesn't get triggered on Wayland at all, so solving this requires a different compositor.

**Comment by ArturKovacs** [comment]
This issue could be quite complex because I think it is related to how images are being processed by the `playback_manager` and the `image_cache` (mod.rs).

But @tuncer if you are interested you can take a look at it and see if there's anything you can find out. Otherwise just let me know and I think I'll investigate it unless @Aloso wants to have a shot at this.

**Comment by Aloso** [comment]
@ArturKovacs I can't reproduce this bug. In debug mode, it can take several seconds to display large images. But it's always shown, unless an error such as #28 occurs.

I noticed that an image can't be displayed if it is renamed while another image in the same folder is opened in emulsion, but I believe this is related to #28 as well.

**Comment by ArturKovacs** [comment]
Now I can't reproduce this either. I don't know what caused or why did I think it was happening. In any case I'm closing this now.
