### ISSUE TITLE
Add SVG support

### ISSUE THREAD

**Issue by ArturKovacs** [ArturKovacs/emulsion#85]
The following aspects should be considered in order of priority

1, Executable performance
2, Minimal dependencies (pure Rust if possible)
3, Reusability for text rendering

Load time should be minimal and zooming and panning should be real-time even with complex svgs.

[Pathfinder](https://github.com/servo/pathfinder) seems to be a strong candiadate. In order to be able to use Pathfinder, managing texture sharing between Pahtfinder's OpenGL context and the main window's OpenGL context has to be sorted out. [Surfman](https://github.com/servo/surfman/pull/179/commits/150e1eb9262cd44b7a8c3bdeb9052f8e8e09eccc) seems to be optimal for this but its winit version should match that of the winit dependecy in `gelatin->glium->glutin->winit`

**Comment by Shnatsel** [comment]
Note that Pathfinder is far from complete in its SVG support, as is Lyon, another GPU-accelerated graphics renderer. Both are able to render very simple SVGs at great speeds, but produce nonsensical output on real-world files.

Both use https://github.com/RazrFalcon/resvg as the SVG parser. It has the nice property of letting you preprocess and simplify the SVG once and then render it multiple times with low latency. The dependency tree is very minimal (especially compared to librsvg) and the only C component it pulls in is HarfBuzz. A pure-Rust alternative to HarfBuzz is in the works (https://github.com/yeslogic/allsorts) and is usable, but does not support all the features yet, and is not wired up to resvg.

**Comment by ArturKovacs** [comment]
Hmm maybe this shouldn't be in the next milestone then.

**Comment by Shnatsel** [comment]
Pathfinder ships with a demo application that loads an SVG and renders it in an OpenGL context: https://github.com/servo/pathfinder/tree/master/demo/native

It does indeed use `surfman`. You can play around with it to evaluate the state of SVG support and/or use it as a code example. It's also a great way to find GPU driver bugs - my entire system locks up when opening certain SVGs in it.
