### ISSUE TITLE
Ship a .desktop file on Linux

### ISSUE THREAD

**Issue by Shnatsel** [ArturKovacs/emulsion#86]
It would be very nice to be able to open images in Emulsion from the file browser, simply by clicking them or via the "Open with..." dialog. On Linux this is accomplished by the program shipping a .desktop file which specifies the name of the program, the icon to use and how exactly it should be invoked.

The [.desktop file specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) and [photo viewer .desktop file sample](https://github.com/elementary/photos/blob/master/data/io.elementary.photos-viewer.desktop.in.in) should be enough to get started.

**Comment by ArturKovacs** [comment]
Yes this would be great. It should be fairly straightforward to extend our distributable-package-building github workflow to automate generating deb packages for Linux. Just like for macos, `cargo-bundle` could be used for this. The resulting deb then could contain a proper .desktop file.

@Shnatsel would you be interested in doing this?

**Comment by Shnatsel** [comment]
I don't have the capacity to drive this, but I have some experience with both .deb packages and .desktop files so feel free to reach out to me if you get stuck or encounter a thorny issue.

**Comment by ArturKovacs** [comment]
This is currently waiting on https://github.com/burtonageo/cargo-bundle/pull/87

**Comment by ArturKovacs** [comment]
Just for transparency, this is now waiting for `cargo-bundle` to have a new release that contains the changes referred to above.

**Comment by ArturKovacs** [comment]
Closed by 929f6021929b69d9da0fa7508208e0002f1b81dc
