### ISSUE TITLE
Add custom thumbnail provider for Windows

### ISSUE THREAD

**Issue by TandersT** [ArturKovacs/emulsion#92]
In windows, a complete transparent image is displayed as if it is black, in the overview in explorer. It is correctly displayed once you open it.

Taking the same image, adding anything (such as a white line) and saving it again, the image is displayed correctly.

**Comment by ArturKovacs** [comment]
So as far as I understand, you are saying that the image is correctly displayed in emulsion but it doesn't appear correctly in the windows file explorer.

Windows generates thumbnails using its own system. However it may be possible to replace that with a custom thumbnail generator. This is something that could be looked into.

**Comment by TandersT** [comment]
Yep that's correct.

It looks like this on my PC
[Issue](https://i.imgur.com/CD5auPa.png)

**Comment by ArturKovacs** [comment]
It is possible register a custom thumbnail provider as described [here](https://docs.microsoft.com/en-us/windows/win32/shell/thumbnail-providers); but I'm still not sure if it's possible replace handlers that already exist in windows like the one for png images.

Even if that's possible, it seems that the effort to implement this is very high relative to the value it brings; especially when compared to some of the other issues that are currently open. With that said I do think that this could be a good addittion at a later time.

**Comment by Shnatsel** [comment]
A thumbnailer based on `image` crate would be a great addition on any platform thanks to the memory safety guarantees of Rust.

But it would probably be best to have it as a separate project rather than associated with `emulsion` because the thumbnailer can be achieved with `image` crate alone, and none of the other dependencies that `emulsion` brings.

**Comment by ArturKovacs** [comment]
I renamed this to better reflect the potential solution of the issue.

On that note, I'm closing this with wontfix because as @Shnatsel noted, this is not something that's within the scope of emulsion.
