### ISSUE TITLE
[Bug] Suddenly unable to display any image

### ISSUE THREAD

**Issue by TandersT** [ArturKovacs/emulsion#94]
I'm unsure how this happened, but Emulsion has completely quit on me. When I open a window nothing shows. All that is displayed in the task bar is this:

https://i.imgur.com/TKR8LdZ.png

After this happened, I have tried restarting, with no change.

I'm not sure how this occurred. Might try re-installing Emulsion if I don't find a fix.

**Comment by TandersT** [comment]
Reinstalling Emulsion doesn't work either.

**Comment by ArturKovacs** [comment]
Check and see if there's a panic.txt file at `%localappdata%\emulsion\data`. If there is please upload its contents as an attachment to a comment.

Also please upload the cache.toml file which you can find at `%localappdata%\emulsion\cache`. Once you uploaded the cache file, I'd suggest removing it and restarting Emulsion.

**Comment by TandersT** [comment]
No panic file.
Deleted it and ran emulsion again, once so it worked.
Here's a copy of the "corrupt" cache file.
[cache - Copy - Copy.txt](https://github.com/ArturKovacs/emulsion/files/4746364/cache.-.Copy.-.Copy.txt)

Changed type to have it be allowed to upload.

**Comment by ArturKovacs** [comment]
Thank youu. Also if you find out what caused this I would be curious to know :D

**Comment by TandersT** [comment]
Possible cause could have been my PC went to sleep, but other than that I'm unsure.
